BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id:input_miles
            text:""
        BoxLayout:
            orientation:"vertical"
            size_hint_x: 0.25
            Button:
                text:"Up"
            Button:
                text:"Down"
    Button:
        text:"Convert miles to km"
        on_press:app.convert_miles_km()
    Label:
        id:output_id
        text:""
        color: (1, 1, 0, 1)